# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
  - main

stages:
  - stage: "Build"
    displayName: "Build the web application"
    jobs:
      - job: "Build"
        displayName: "Build job"
        pool:
          vmImage: ubuntu-latest
          demands:
            - npm

        steps:
          - task: NodeTool@0
            inputs:
              versionSpec: "16.x"
            displayName: "Install Node.js"

          - script: |
              npm install
              npm run build
              echo $PWD
            displayName: "npm install and build"

          - task: ArchiveFiles@2
            inputs:
              rootFolderOrFile: "/home/vsts/work/1/s/build/"
              includeRootFolder: false
              archiveType: "zip"
              archiveFile: "$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip"
              replaceExistingArchive: true

          - task: PublishBuildArtifacts@1
            inputs:
              PathtoPublish: "$(Build.ArtifactStagingDirectory)"
              ArtifactName: "drop"
              publishLocation: "Container"


  - stage: "Dev"
    displayName: "Deploy to the dev environment"
    dependsOn: Build
    jobs:
      - deployment: Deploy
        pool:
          vmImage: "ubuntu-20.04"
        environment: dev
        variables:
          - group: Release
        strategy:
          runOnce:
            deploy:
              steps:
                - download: current
                  artifact: drop
                  
                - script: |
                    echo $(Pipeline.Workspace)
                - task: AzureWebApp@1
                  displayName: "Azure App Service Deploy: website"
                  inputs:
                    azureSubscription: "Devops - Demo"
                    appType: 'webApp'
                    appName: "$(WebAppNameDev)"
                    package: "$(Pipeline.Workspace)/drop/*.zip"






